Fixed the Monitor particles being ugly when broken and added some other break particles to make it nicer.
Loqor/ait pull request #335
Opened 2024-08-03 20:17 UTC by MaketendoDev

![Thing](https://media.discordapp.net/attachments/1213989171241426954/1269167347457982505/image_1.png?ex=66afbc73&is=66ae6af3&hm=4399d29497a7f0fde1090370d8b836926d7cd7676545e3fb218dbdb6f6204da0&=&format=webp&quality=lossless)

2024-08-05 16:13 UTC, MaketendoDev commented
guh

2024-08-05 19:51 UTC, MaketendoDev commented
no LGTM's 😢

2024-08-06 12:19 UTC, Duzos commented
LBTM

2024-08-06 12:21 UTC, Duzos requested changes
directory changes

2024-08-06 12:21 UTC, Duzos commented on src/main/resources/assets/ait/models/block/detector_block.json
> +		"particle": "ait:block/block_particles/detector_block"
put them into block/particles instead of block/block_particles
we already know it’s for blocks..

2024-08-06 12:21 UTC, Duzos commented on src/main/resources/assets/ait/textures/block/block_particles/detector_block.png
textures LGTM but i’m no expert

2024-08-06 12:53 UTC, MaketendoDev commented
dunnit

2024-08-07 10:46 UTC, Duzos commented
ok LGTM

2024-08-07 10:46 UTC, merged